name: Scan

on:
  release:
    types: [published]
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  scanPush:
    uses: root-de/scan-action/.github/workflows/scan.yml@main        
